export default interface BasketballPlayer {
    playerName: string, 
    teamName: string, 
    id: string,
    age: number, 
    bpm: number, 
    dbpm: number, 
    dws: number, 
    g: number, 
    mp: number, 
    obpm: number, 
    ows: number, 
    per: number, 
    pos: string, 
    rk: number, 
    tspercent: number, 
    usgpercent: number, 
    vorp: number, 
    ws: number, 
    ws_48: number, 
}